name: Pull Request Check

on:
  pull_request:
    branches: [ develop, main, desktop ]
    paths-ignore:
      - 'README.md'
      - 'doc/*'

jobs:
  check:
    runs-on: ubuntu-latest

    env:
      NPM_TAG: latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm ci

      - name: Test
        env:
          JEST_JUNIT_OUTPUT_DIR: test-results/unit
        run: npm run test:lint -- --quiet --output-file test-results/eslint/results.xml --format junit
        run: npm run test:unit -- --reporters="default" --reporters="jest-junit" --coverage --coverageReporters=text --coverageReporters=lcov --maxWorkers="2"

      - name: Build
        env:
          NODE_ENV: production
          GA_ID: ${{ secrets.GA_ID_ONLINE }}
          NODE_OPTIONS: --max-old-space-size=4000
        run: npm run build
